#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DOTFILESDIR=${ZDOTDIR:-$HOME}/z/src/dotfiles/master
export HOMEBREW_CASK_OPTS="--appdir=/opt"

unset SSH_AGENT_PID
export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh

export NVM_DIR="$HOME/.nvm"

# needed for alot
export LC_ALL=en_US.UTF-8

# needed zsh autosuggestions fg color under tmux
export TERM=xterm-256color

export PASSWORD_STORE_DIR=~/z/documents/passwords
export PASSWORD_STORE_ENABLE_EXTENSIONS=true

export MYSQL_HISTFILE=~/z/documents/histories/mysql_history
