#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${DOTFILESDIR:-$HOME/dotfiles}/modules/shell/externals/prezto/init.zsh" ]]; then
  source "${DOTFILESDIR:-$HOME/dotfiles}/modules/shell/externals/prezto/init.zsh"
fi

# Customize to your needs...
alias gw='./gradlew'
alias gwValidate='./gradlew validate findbugsMain'

function tm() {
  [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
  if [ $1 ]; then
    tmux $change -t "$1" 2>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1"); return
  fi
  session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0) &&  tmux $change -t "$session" || echo "No sessions found."
}

function setupIdeaForDM() {
  echo "Clean Workspace"
  gw clean $@ || return;
  echo "Setup Hadoop..."
  gw setupHadoop $@ || return;
  echo ""
  echo "Compile Integration Tests..."
  gw compileIntegTest $@ || return;
  echo""
  echo "Generate Idea Project Files..."
  gw idea $@ || return;
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# this make the opening of a shell slow, think about to move it out
#. /usr/local/opt/nvm/nvm.sh

if [ -z "$TMUX" ]; then
  if tmux has-session 2>/dev/null; then
    echo "There are tmux sessions attached..."
  else
    tmux new-session -d -s dev -c "$HOME/z/src/dap/master" -n topics
    tmux new-session -d -s etc
    tmux new-window -c "$HOME/z/src/dap/master" -t dev:1 -n master
    tmux new-window -c "$HOME/z/src/dap/v7.2" -t dev:2 -n v7.2
    tmux new-window -c "$HOME/z/src/dap/v7.1" -t dev:3 -n v7.1
    tmux new-window -c "$HOME/z/src/dap/v6.4" -t dev:4 -n v6.4
    tmux select-window -t dev:1
  fi
fi

alias glol="git log --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

alias lockMyScreen="/System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine"

alias t="task"
# this line is required to show vim mode in prompt 'pure'
# See https://github.com/sindresorhus/pure/wiki
PROMPT='%(?.%F{magenta}.%F{red})${editor_info[keymap]} '

eval "$(jenv init -)"

alias scala="scala -Dscala.shell.histfile=$HOME/z/documents/histories/scala_history"
alias hive_1_1="HADOOP_HOME=\"/opt/hadoop-2.6.0\" HADOOP_USER_CLASSPATH_FIRST=true HADOOP_CLIENT_OPTS=\"-Duser.home=$HOME/z/documents/histories\" bin/hive"
alias beeline_1_1="HADOOP_HOME=\"/opt/hadoop-2.6.0\" HADOOP_USER_CLASSPATH_FIRST=true HADOOP_CLIENT_OPTS=\"-Duser.home=$HOME/z/documents/histories\" bin/beeline"
