#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${DOTFILESDIR:-$HOME/dotfiles}/modules/shell/externals/prezto/init.zsh" ]]; then
  source "${DOTFILESDIR:-$HOME/dotfiles}/modules/shell/externals/prezto/init.zsh"
fi

# Customize to your needs...
